export { default as Login } from './login/Login'
export { default as NotFoundPage } from './ErrorPage/NotFoundPage.jsx'
export { default as Adding } from './adding/Adding'
export { default as Eadmins } from './admins/Eadmins.jsx'
export { default as Branches } from './branches/Branches'
export { default as Companies } from './companies/Companies'
export { default as Unauthorized } from './unauthorized/Unauthorized'
export { default as Courses } from './courses/Courses'
export { default as Creatinig } from './createing/Creatinig'
export { default as Dashboard } from './dashboard/Dashboard'
export { default as Groups } from './groups/Groups.jsx'
export { default as Stafs } from './stafs/Stafs'
export { default as Students } from './students/Students'
export { default as Archive } from './archive/Archive'
export { default as Profile } from './profile/Profile'

